import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Medusa Sweatpants",
    icon: "checkroom",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 4,
    status: "Publicado",
  },
  {
    id: "2",
    name: "Medusa Jeans",
    icon: "checkroom",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 5,
    status: "Publicado",
  },
  {
    id: "3",
    name: "Medusa Sweatshirt",
    icon: "checkroom",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 4,
    status: "Publicado",
  },
  {
    id: "4",
    name: "Medusa Hoodie",
    icon: "checkroom",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 5,
    status: "Publicado",
  },
  {
    id: "5",
    name: "Medusa T-Shirt",
    icon: "checkroom",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 8,
    status: "Publicado",
  },
  {
    id: "6",
    name: "Medusa Backpack",
    icon: "backpack",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 3,
    status: "Publicado",
  },
  {
    id: "7",
    name: "Medusa Watch",
    icon: "watch",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 3,
    status: "Publicado",
  },
  {
    id: "8",
    name: "Echo Dot",
    icon: "speaker",
    collection: "-",
    salesChannel: "Default Sales Channel",
    variants: 3,
    status: "Publicado",
  },
];
